name: eth_irrig
channels:
  - anaconda
dependencies:
  - python=3.7
  - pip
  - pip:
    - tensorflow==2.5
    - ipython
    - pandas
    - geopandas
    - tqdm
    - rasterio==1.1
    - openpyxl
    - scikit-learn
    - catboost
    - yaml